### ISSUE TITLE
App Crashes while the touch the action button for control in EPUB loaded Activity

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [readium/r2-testapp-kotlin#284]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.creaplay_native, PID: 9145
    kotlin.KotlinNullPointerException
        at org.readium.r2.navigator.epub.R2EpubActivity$toggleActionBar$1.invokeSuspend(R2EpubActivity.kt:469)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mickael-menu** [comment]
`R2EpubActivity` is here for backward compatibility purpose but the proper way to integrate Readium in the latest versions (`develop`) is to use `EpubNavigatorFragment` and handle toggling toolbars in your own activity.
