### ISSUE TITLE
Conflict on libc++_shared.so between liblcp and PDFiumAndroid

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-testapp-kotlin#320]
It looks like there's a conflict between the latest version of [PDFiumAndroid](https://github.com/barteksc/PdfiumAndroid/) 1.9.0 and liblcp. When building, I get this error:

> More than one file was found with OS independent path "lib/arm64-v8a/libc++_shared.so"

I managed to build by adding these settings in the `build.gradle` of the app:

```
packagingOptions {
    pickFirst 'lib/x86/libc++_shared.so'
    pickFirst 'lib/x86_64/libc++_shared.so'
    pickFirst 'lib/arm64-v8a/libc++_shared.so'
    pickFirst 'lib/armeabi-v7a/libc++_shared.so'
}
```

But then, the LCP lib crashes with this error:

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__sfp_handle_exceptions" referenced by "/data/app/org.readium.reader-9khTthf02oLgGERC1SDuCQ==/lib/arm64/liblcp.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.readium.lcp.sdk.Lcp.<clinit>(Lcp.kt:32)
        at org.readium.r2.lcp.license.LicenseValidation$isProduction$1.invoke(LicenseValidation.kt:118)
```

However, it works with an older version of PDFiumAndroid, so now we're stuck with PDFiumAndroid 1.6.1 (instead of 1.9.0) and AndroidPdfViewer 2.8.2 (instead of 3.2.0).

Any help is most welcome.

**Comment by mickael-menu** [comment]
@danielweck Do you have any idea if there's something that could be done on the liblcp side to address this problem? Thanks

**Comment by danielweck** [comment]
I think, more likely something @aferditamuriqi can help with, because Android.
I am only familiar with the NodeJS and plain UNIX LCP native lib builds.

**Comment by danielweck** [comment]
See Slack discussion for further analysis of the LCP build issue

**Comment by mickael-menu** [comment]
According to @danielweck , this pull request could address a similar issue: https://github.com/readium/readium-lcp-client/pull/49

> Gradle tweaks to “pick” native lib dependency … but cannot remember the exact pattern

**Comment by danielweck** [comment]
I think you meant https://github.com/readium/SDKLauncher-Android/pull/152/files

**Comment by danielweck** [comment]
Alternatively, maybe some inspiration in this PR, but I doubt so https://github.com/readium/SDKLauncher-Android/pull/147/files

**Comment by danielweck** [comment]
it’s been a long time since I rewrote the Gradles to integrate ReadiumSDK and ReadiumLCP (Readium1) for Android build matrix ARM/x86 32/64 release/debug … I do not remember all the techniques in the PR (…I imagine the Gradle / NDK syntax evolved since then)

**Comment by cursem** [comment]
@mickael-menu Hi, Have you solved this problem？

**Comment by mickael-menu** [comment]
@cursem No, I didn't spend more time on this. Let us know if you tackle this.

**Comment by cursem** [comment]
> @cursem No, I didn't spend more time on this. Let us know if you tackle this.

You should make sure compile liblcp and PDFiumAndroid with the same ndk version.

**Comment by mickael-menu** [comment]
I tried again upgrading AndroidPdfViewer and liblcp doesn't seem to crash anymore, after adding the following in the `build.gradle`:

```
packagingOptions {
    pickFirst 'lib/x86/libc++_shared.so'
    pickFirst 'lib/x86_64/libc++_shared.so'
    pickFirst 'lib/arm64-v8a/libc++_shared.so'
    pickFirst 'lib/armeabi-v7a/libc++_shared.so'
}
```

It could have been fixed after upgrading to Gradle 7, but will need more testing to make sure there's no issue on older Android versions.
