### ISSUE TITLE
After migrating to 2.0.0 from 2.0.0-beta1 getting this error. Which was working fine before migrating

### ISSUE THREAD

**Issue by ajay9889** [readium/r2-testapp-kotlin#423]
![Screenshot_1621533187](https://user-images.githubusercontent.com/9216373/119029270-0226b680-b9db-11eb-95bb-45b7c98fdaef.png)
Please help me to fix this error

E/NanoHTTPD: Communication with the client broken, or an bug in the handler code
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.nanohttpd.protocols.http.response.Response org.nanohttpd.router.RouterNanoHTTPD$UriResource.process(java.util.Map, org.nanohttpd.protocols.http.IHTTPSession)' on a null object reference
        at org.nanohttpd.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:597)
        at org.nanohttpd.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:672)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:376)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:372)
        at org.nanohttpd.protocols.http.NanoHTTPD.handle(NanoHTTPD.java:535)
        at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:418)
        at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
        at java.lang.Thread.run(Thread.java:920)

**Comment by ajay9889** [comment]
It baseUrl the URL issue. Now, I have fixed it. Thanks

**Comment by mickael-menu** [comment]
You should check out the migration guide when upgrading: https://readium.org/mobile/kotlin/migration-guide#serving-publications-with-the-http-server

Although now that 2.0.0 is out, future versions should be painless until 3.0.0.
