### ISSUE TITLE
java.lang.NoSuchMethodException: org.readium.r2.testapp.reader.e.<init>

### ISSUE THREAD

**Issue by mrifni** [readium/r2-testapp-kotlin#433]
Error on release apk version but debug version works. Tested same apk file on Oneplus 5 Android 10 (Oxygen OS 10.0.1) works but Oneplus 6 Android 10 (Oxygen OS 10.3.11) crashes the app with the below message.

I am using latest develop branch test app kotlin in my app.
```
E/AndroidRuntime(19003): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mybookstore/org.readium.r2.testapp.epub.EpubActivity}: java.lang.NoSuchMethodException: org.readium.r2.testapp.reader.e.<init> [class android.content.Context, class org.readium.r2.testapp.reader.d$b]
E/AndroidRuntime(19003):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
E/AndroidRuntime(19003):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
E/AndroidRuntime(19003):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(19003):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(19003):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(19003):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
E/AndroidRuntime(19003):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19003):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(19003):        at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(19003):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19003):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(19003):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(19003): Caused by: java.lang.NoSuchMethodException: org.readium.r2.testapp.reader.e.<init> [class android.content.Context, class org.readium.r2.testapp.reader.d$b]
E/AndroidRuntime(19003):        at java.lang.Class.getConstructor0(Class.java:2332)
E/AndroidRuntime(19003):        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
E/AndroidRuntime(19003):        at org.readium.r2.testapp.reader.e$b.a(Unknown Source:18)
E/AndroidRuntime(19003):        at androidx.lifecycle.p0.b(Unknown Source:37)
E/AndroidRuntime(19003):        at androidx.lifecycle.p0.a(Unknown Source:23)
E/AndroidRuntime(19003):        at org.readium.r2.testapp.epub.EpubActivity.onCreate(Unknown Source:52)
E/AndroidRuntime(19003):        at android.app.Activity.performCreate(Activity.java:7815)
E/AndroidRuntime(19003):        at android.app.Activity.performCreate(Activity.java:7804)
E/AndroidRuntime(19003):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
E/AndroidRuntime(19003):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
E/AndroidRuntime(19003):        ... 11 more
```

**Comment by mrifni** [comment]
this could be a proguard issue....
